### ISSUE TITLE
Use @v3 tag to bring it in line with github actions nodejs/version schema

### ISSUE THREAD

**Issue by luigimannoni** [benoitchantre/setup-ssh-authentication-action#1]
Might sound very stupid, but can this be retagged as v3? This will be in line with the v3 schema github base actions are providing, currently the action works only if you launch it as `benoitchantre/setup-ssh-authentication-action@1.0.0` 

So I know all v3 are running on nodejs v16 :)

**Comment by benoitchantre** [comment]
@luigimannoni I understand the reasoning, but this would not follow semantic versioning (v1.0.0 is the first public release).

This action is a composite action and uses bash only. It doesn’t require any specific version of Node and will probably require near to 0 maintenance.
