### ISSUE TITLE
Readme contains wrong version tag

### ISSUE THREAD

**Issue by yubiuser** [benoitchantre/setup-ssh-authentication-action#2]
In your readme you use

` uses: benoitchantre/setup-ssh-authentication-action@v1`

However, there is no tag `v1` but only `1.0.0.` (also note the missing `v`)

So the correct line is

` uses: benoitchantre/setup-ssh-authentication-action@1.0.0`

**Comment by benoitchantre** [comment]
@yubiuser Thank you for raising the issue.
